### ISSUE TITLE
Uncaught TypeError: this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by duckworth** [ni3galave/react-x-editable#13]
I am getting the error in the Editable onSubmit method:

`Uncaught TypeError: this.updater.enqueueCallback is not a function` 

I am using 0.0.9-beta in my project with React 16 when trying to use the handleSubmit property. 

If I use the version currently in master the error goes away. 

Would it be possible for you release what is currently in master as 0.0.10-beta ?

**Comment by ni3galave** [comment]
[Added support for React 16+.](https://github.com/ni3galave/react-x-editable/releases/tag/v0.0.10-beta)

Please let know if you face any issue.

**Comment by duckworth** [comment]
Works now. Thanks!
