### ISSUE TITLE
Validation failed even if  there is value in field 

### ISSUE THREAD

**Issue by sachinpatil55** [ni3galave/react-x-editable#18]
steps - 
1) go to type 2)Empty text field, required - Add some text and click ok
2) then open same field and clear value and click on  close icon 
3) again open same editable and click on ok 
validation failed even if there is text in field
![screenshot from 2019-01-19 13-22-31](https://user-images.githubusercontent.com/29506306/51423966-5348f480-1bed-11e9-85a9-52ef45b63cdb.png)

**Comment by ni3galave** [comment]
Merged : https://github.com/ni3galave/react-x-editable/pull/19
