### ISSUE TITLE
Add support for onChange event for select or any other data type

### ISSUE THREAD

**Issue by gotyet9** [ni3galave/react-x-editable#2]
<Editable
                        dataType="select"
                        name={"city"}
                        mode={"popup"}
                        value={2}
                        title="Please select city"
                        placement="right"
                        showButtons={true}
                        options={[
                            { value: 1, text: "Mumbai" },
                            { value: 2, text: "Pune" },
                            { value: 3, text: "Nashik" }
                        ]}
                        onChange={this.updateLineItemsTable.bind(this)}

Above is the way im trying to fire an event on onChange of the select drop-down. But nothing happens as such. i want to fire an event to dynamically change other fields value on the basis of drop-down value.

**Comment by ni3galave** [comment]
I have fixed issue needs to go through the testing process once done I will update the repo.

Thanks for reporting issue/feature!!

**Comment by ni3galave** [comment]
Added support for onChange event for all data types as **_onInputChange_**
This enhancement will be available in latest release. 
Fixed : https://github.com/ni3galave/react-x-editable/commit/2fb2d64e2dcafd554884499d9b390d39faf771ab

Thanks!

**Comment by gotyet9** [comment]
Thanks for your response.
