### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by YassienW** [ni3galave/react-x-editable#20]
The latest release was 8 months ago and pop ups are still broken (#4)

**Comment by ni3galave** [comment]
Hi @YassienW 
I am a little overloaded past couple of months. So I did not get a chance to look into a couple of raised issue. Sorry for the inconvenience or late reply. 

I am excited to add support for bootstrap4. It would be greatly appreciated if you raise PR for bootstrap 4 support.

**Comment by YassienW** [comment]
I have done 2 changes related to bs4 that i will submit a PR for, i won't be able to contribute more though since i started my own similar project aimed at bs4.

**Comment by ni3galave** [comment]
No worries. Best luck for your project 👍
