### ISSUE TITLE
dataType select duplicates entry and throws error

### ISSUE THREAD

**Issue by dariobanfi** [ni3galave/react-x-editable#22]
Any `EditableField` with `dataType="select"` causes this Warning to be thrown when submitting the changes 

`Warning: Encountered two children with the same key, `option-select`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version`

This also causes the select to add duplicate "select" option items.

**Comment by ni3galave** [comment]
Thanks for raising the issue.

**Comment by dariobanfi** [comment]
Would you like a ME for this ? (And merge it and publish a new version?)

**Comment by ni3galave** [comment]
Yeah, PR are always welcome :) but I just committed the same changes before your reply https://github.com/ni3galave/react-x-editable/commit/545aac170369e8840e388515ace9724a4e8517bc :(
I will publish soon.

**Comment by dariobanfi** [comment]
Hey @ni3galave, thanks for your fix. Any info on when you're going to release a new version? I would like to use your library, but if you need more time then I will have to fork it
