### ISSUE TITLE
No option for new line in textarea

### ISSUE THREAD

**Issue by joshreep** [ni3galave/react-x-editable#24]
As a dev user, I would like the ability to create a new line when using the textarea component.  Currently, If the user presses "return", (`keycode == 13`), the onSubmit handler is called.  I would like to make this functionality optional; to be controlled by a `submitOnReturn` prop which would be a boolean and default to `true`.  I'm happy to submit a PR.

**Comment by ni3galave** [comment]
Good have this functionality.

PR are always welcome :)

**Comment by joshreep** [comment]
@ni3galave I have made the changes. I wanted to update the Documentation with the new prop.  I was trying to figure out where the documentation is.  Does it live in a separate repo?

**Comment by ni3galave** [comment]
@joshreep
Yeah, documentation is in live repo. I will update the document once PR is merged. 
Also, I will add the documentation somewhere so that contributors able to update the document part as well. 

Thanks for the PR. :) I'll look into it.

**Comment by joshreep** [comment]
@ni3galave Any update on this?

**Comment by ni3galave** [comment]
There is minor release is going to happen. Once it is done I will update the doc for the same.

**Comment by joshreep** [comment]
Sounds good.  Thanks!
