### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by HWGehring** [ni3galave/react-x-editable#30]
There's a select fix that we really need in order to move development forward. Would you mind tagging a new release? Thanks

**Comment by createthis** [comment]
@ni3galave ^

**Comment by ni3galave** [comment]
You can create a user-defined component (i.e Select2) with use of prop type="custom".
See doc for more information: https://doc-react-x-editable.stackblitz.io/

**Comment by createthis** [comment]
@ni3galave I'm more interested in tagging a release due to the removal of npm as a dependency. Lots of security issues lately and that would help.

**Comment by hwperkins** [comment]
@ni3galave we ended up forking
