### ISSUE TITLE
React 16 warning about javascript in href attribute

### ISSUE THREAD

**Issue by iceberk** [ni3galave/react-x-editable#31]
Hi,

React 16.13.1 now shows a warning when passing "javascript:" to `<a href>`:

> Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:;"

Can't we just omit href and call e.preventDefault in onClick handler?

**Comment by tc-modist** [comment]
I don't think this is fixed, I'm still getting this error as well

**Comment by iceberk** [comment]
Yes, later I noticed that my patch doesn't solve the problem. I'm afraid we need another solution.
